name: Fetch and build Budgy layout

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-and-build-budgy-layout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4

      - name: Update QMK firmware submodule
        run: |
          git submodule update --init --recursive --depth=1

      - name: Download Budgy config
        run: |
          mkdir -p budgy
          curl -L https://raw.githubusercontent.com/qmk/qmk_firmware/master/keyboards/budgy/config.h -o budgy/config.h
          curl -L https://raw.githubusercontent.com/qmk/qmk_firmware/master/keyboards/budgy/keyboard.json -o budgy/keyboard.json

      - name: Append custom config values
        run: |
          cat << 'EOF' >> budgy/config.h

          #undef TAPPING_TERM
          #define TAPPING_TERM 220
          #define QUICK_TAP_TERM 0
          #define COMBO_COUNT 4
          #define TAPPING_TERM_PER_KEY
          EOF

      - name: Create rules.mk
        run: |
          cat << 'EOF' > budgy/rules.mk
          TAP_DANCE_ENABLE = yes
          CAPS_WORD_ENABLE = yes
          COMBO_ENABLE = yes
          EOF

      - name: Copy i18n.h
        run: |
          cp 34RRD/i18n.h budgy/keymaps/moonlander/i18n.h

      - name: Copy keymap.c
        run: |
          cp 34RRD/keymap.c budgy/keymaps/moonlander/keymap.c

      - name: Parse moonlander keymap
        run: |
          python3 moonlander_budgy_parser.py

      - name: Parse moonlander keymap
        run: |
          python3 moonlander_budgy_parser.py

      - name: Commit and Push changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add .
          git commit -m "✨(budgy): Update config" || echo "No layout change"
          git push

      - name: Build qmk docker image
        run: docker build -t qmk .

      - name: Build the budgy layout
        id: budgy-build-layout
        run: |
          # Copy layout files to the qmk folder
          rm -rf qmk_firmware/keyboards/budgy
          mkdir -p qmk_firmware/keyboards/budgy
          cp -r budgy qmk_firmware/keyboards/
          
          # Build the layout
          docker run -v ./qmk_firmware:/root --rm qmk /bin/sh -c "
            qmk setup budgy -y
            qmk compile -kb budgy -km moonlander
          "
          
          # Find and export built layout          
          # budgy_moonlander.uf2

          echo budgy_built_layout_file=./qmk_firmware/budgy_moonlander.uf2 >> "$GITHUB_OUTPUT"

      - name: Upload budgy layout
        uses: actions/upload-artifact@v4
        with:
          name: budgy_moonlander
          path: ${{ steps.budgy-build-layout.outputs.budgy_built_layout_file }}
